required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "v3.2.11"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.11.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "go.uber.org/zap"
  version = "v1.7.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.1.4"

[[constraint]]
  name = "github.com/oklog/run"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "v1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "v1.3.0"

# the following constraint is a temporary hack until
# the following issue is resolved:
# https://github.com/golang/dep/issues/1457
[[constraint]]
  name = "github.com/apache/thrift"
  revision = "b2a4d4ae21c789b689dd162deb819665567f481c"
