---

apiVersion: v1
kind: Service
metadata:
  name: kanali
  namespace: default
spec:
  selector:
    k8s-app: kanali
  ports:
  - name: https
    port: 8443
  - name: http
    port: 8080
  type: NodePort

---

apiVersion: v1
kind: Secret
metadata:
  name: kanali
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDempDQ0FiYWdBd0lCQWdJSkFLWXh2bGVwaFZyVU1BMEdDU3FHU0liM0RRRUJDd1VBTUJZeEZEQVNCZ05WDQpCQU1NQzJWNFlXMXdiR1V1WTI5dE1CNFhEVEUzTURRek1ESXlOREUxT1ZvWERURTVNRFF6TURJeU5ERTFPVm93DQpGakVVTUJJR0ExVUVBd3dMWlhoaGJYQnNaUzVqYjIwd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3DQpnZ0VLQW9JQkFRRDVuM1NwUTI5T1dkNUEvbXJFeHh5OGN5ek42WTRTcEFrVjZ4SmsyKzRMRFg5RnZxbGo3NVhqDQpjd3VnY0U1bmhHOHZaWWJMSkRwTFd1cWFUUUtHMGpmN3lNK3pSQ0FzR0dNQ1NPQUczNmZIYThmMU5ZUzh2elVHDQpmVUtLRzJ5OFpWYU9aaHJOOERld1RkOGJIRFJCakllcTVQMjhaZHdqdDJDSSsvMHdBbTlHT1RQa25JMnpWUDdSDQpROVBEcnYxTU55Z0RtRnUyUmx6dFdtbTAxM0x3Z0dEVXRWOXJmd0FnbVpFc29iMUVsK3VWeFlRREZZMGx6a3BRDQpVdGNpR0tMV283TUNUV3ZmY1ZHc0hKelZWL29ydDZERlN3TlJOY0swZWh1ZzduaHlOYUttTzFlRE1QKzgzR285DQpFeXArMlVJYXovYjJtQ3QrT3E4c1ZLN0pZZWttV05hakFnTUJBQUdqSHpBZE1Cc0dBMVVkRVFRVU1CS0hCTUNvDQpZMlNIQk1Db1kyV0hCTUNvWTJZd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLdEtBMDJVK1BEQVQ0TnNGMjlXDQpOazYzTFkzM2RmSFdPSUs1QjFDMzhpTEdJQU9YT1A5cWlBZHJ5NHFIN3RDOUJtb3FYcVdSZnJ2S2NFdTA3bDc4DQp5N1lGK1RQTUtNY0ZnaXRDbmQydVFTSk52VUM2aDBSaVg4NjI3SWZDaUlVNG5oWXVvOEk3TkZaOWlCdXNac2xyDQo1S2dEODdyTUxvL3UrQitobkpEZjRUSStpNnhuMjd0Z3dqeWlrbGJRUFlXZ1VFK3FNYVVaZGVEVTBmT1lEN09xDQpoay8zdkJaQlkxcGhHeS9GckZLYnJEazA1ellNT05JSDlvUjJIOUpRdnF6VzVOQ2Z6M3dpZGpqZFZ4aUloMzlWDQp5eW5rQ2VpN1VCa0MvZnRPcDd1dTRjdXoxN1I5aFc3ZjhDZHNtcWZidkZhcVkzVHVzTnlzL0lFRmdyN3p5RHc4DQo0Y289DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW93SUJBQUtDQVFFQStaOTBxVU52VGxuZVFQNXF4TWNjdkhNc3plbU9FcVFKRmVzU1pOdnVDdzEvUmI2cA0KWSsrVjQzTUxvSEJPWjRSdkwyV0d5eVE2UzFycW1rMENodEkzKzhqUHMwUWdMQmhqQWtqZ0J0K254MnZIOVRXRQ0Kdkw4MUJuMUNpaHRzdkdWV2ptWWF6ZkEzc0UzZkd4dzBRWXlIcXVUOXZHWGNJN2RnaVB2OU1BSnZSamt6NUp5Tg0KczFUKzBVUFR3Njc5VERjb0E1aGJ0a1pjN1ZwcHROZHk4SUJnMUxWZmEzOEFJSm1STEtHOVJKZnJsY1dFQXhXTg0KSmM1S1VGTFhJaGlpMXFPekFrMXIzM0ZSckJ5YzFWZjZLN2VneFVzRFVUWEN0SG9ib081NGNqV2lwanRYZ3pELw0Kdk54cVBSTXFmdGxDR3MvMjlwZ3JmanF2TEZTdXlXSHBKbGpXb3dJREFRQUJBb0lCQUVOQTQ5U0t0NTFiZHhiNQ0KdE5ocGNPT1JBRnhGOWFJdUVjaVcrZkMwbEhEajVRdHNjQVRkMHZ0aHpwc2VSdkY2NjkzUU03M2RkOXMvbG4rVw0KQ2YwNi9CeFpJU1NDVVV5d0VWVFhQNHg2aTZDZCtGU25ZNmphdHpXVlgrMEhzSWNkb25GaEx3MlhEOW52VVJIag0KeW14eXFVYXd4WEFSM1hxOStFTlA2UW9iVGRHVUphQlE1MlZJN1B0dm8wV3hmM0dyUWs0Z3ZpZ2FHM0JDNUI3OQ0KTW1TYnhLNXdOOURycm1meGZ1MjFSVU00Y005ZG1iU2ZvNTEzVU9Vdm1Ya3d3c3F3M01GVTRLd0dUVi8xdXN1Uw0KbkJLZTJkcWhKMThOd1dNaGpuWlJWMEcrTTRLSkttcnV3cXRlVWFENDl5ZmZSUXpLRDRhazBDK2tqZnpNRWRTQg0KdXZSSTJ0RUNnWUVBL2ZBb2RrbnhFN2l0WmVNMnoxeVJKWE5CVnNVcFJ5NjY0QWxaNXBRSjRSQjhmZ1NLa0Y4NQ0KZUw5VmZ5enFSVldQQkxCaVhRdG9EMTVxL2JGcDZxUlNDWXd0b0M0R3J3VEtFUERvUmNyVEorelVCeXpMZTYzSg0KV0w0ZE1SUG5JcUZCL3E3SkVGc3dMbmNzbDd6R1RtaHdrclJkaEoyeE51djd2Z3RHNEpaRU84c0NnWUVBKzZaVA0KOEI0MS8ycnVHeG1nT09pNDliM1Y1RHhJMVdVYXpHaUF0Qk5ORmxEZm8zWnE0bkdtU05XZ1NuQW5COGo0cFU1Tg0KU2ZzK09VRit5Si84MmlqMVBmZDhNYzZ3ZTd4ZmJMZFhFNmpHOGp3S1ZVcGUwVGFGbHpRdm1RSWFvcUdUdHBOWg0KUVAzaE9iMHhaZTVjVytXSlJmSldZOVJWUUdJdm83dVRJZUNCcFlrQ2dZRUF4TlVWbC9MaWtlWFJTaXVmdllYRA0KNENLQlgrKzllamFIbGNiSno0ZXFUTEVKdm1ob3UxV0VaOHJ2UzMrV0s1NFJHSkpiL0VFdUxOT0QzUmRhd1EwVA0KcGVEcE1NTGNYV2M1OVgyMm5QcUZSK296dzBmK2hlU0VNR3hVbGtrV0hPcWdDL2lSVTBOTGlvakhvT29yVUhWMQ0KNU5FM3QrYS9pWkhMZFZpcVhNVTlLSmNDZ1lBWjZENjkrcTQrZEdpOCszOW1QSGRHUFZ2MjJrbjVSaVpqSXVNVg0KSnVPSng1dXVmWE4xaXBPKzdkZEpzcEFpR2d1WElSK04zVUxEckQxOE5CUlk5VnlDRzZkNmpUZllGVVdSc0xKVA0KUU0zeWhFSGdFLzc4OU9yOTdRNTFaeVVNMXl1WTRVU1FEMU1QbWEyck84WGdaQm9rekZVZWcrNmU2VHpVVTJ4TA0KVVl5bldRS0JnQWg0UnN3dXBqMzVsakUyY0dLa2ZpODBCTHR4b3ZvMzZVbmJtTWY1eFZQaTJLRmtxSWZUelZRbw0KQ3hEWHQ4R1ZWOTViTTZQOUNDODhNWks3MERkZXFZdWtxaG9DRDRIUzFVaUloaitEcEhzMU16MmxJVUZ0QWhTQg0KMGFwc2JDejloTGdMakNEbkFORzFsVGJSR0FVblQvb1o4azJSUytwMldxak9SS2t0ZXhiMA0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0=

---

apiVersion: v1
kind: Secret
metadata:
  name: kanali-key-decription
  namespace: default
type: Opaque
data:
  key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRXBRSUJBQUtDQVFFQXlxT3ZLYVFtT0o1cDVOdmtPSm5YNURJdFhlTWxWcjJablBnOURLUGkxVGI0WDUwRg0KL2dCMC9uRVI4VCtxUGJ2eWViR1FQVjNPcXZNSHJDYUp0ZmE1VmlYVUZzc2lxSm1LTTkrU3ZpY1ErcGNHdkhEWg0KVDVHTUVXaWZWUTAyK1pOaUZ5ZmxQY0k0NVM4VGZVaGlNRmFBaDFRVHkvZ1ZRcFA0RUZYUGZwQ3U2OGJyNCtrTA0KWXRUS1dvbkdFaDZ1cFcvRy94MDNxRnRhdGh1emFQTEdyTVdGQ2xZbGljMjhjbDB6MUZ2aWtDZ1hGZmYxTWE0MQ0KTHM5RWUyMGRxV3RrTlEzSFFsQnRhWGlKMkRTRGZjYWYxMEYycmc4QjQ4eFhxRnF4QlY4aTE0WmgvMUt4NkJMZg0KUVJuWGNsM2g4cys4MjE2MWsyQXVRdnNWM2s3WnVIRU5tTHFjb1FJREFRQUJBb0lCQVFDRjQ1MEs0SUM0akVMZg0KaWtMQyt6TmdmWjdvRi90RjBzUzZxSEo5OVpNYzJkTkdLWlFaL2VkUGJ4b3gwcVVEWVRtWEdyRjVPcEFnOTY4cw0KR2RLSHZsczdCb2VaLytJSWtGcDJaOVNuZTF5R2xsOUhCekV1bDdaNmtpd2tvRFNndHJicklkc2Y4VUp5ZTZaZQ0KOHdLZGVhbzJ3R0RNTmtDbDJ1cmVzRFFISmtYTlZsWjhVaUdIMGR2UFZHVEdpaFFBWnJxOXM2MkhhRUZwaG8wNQ0KRTdBU0xkZ00rQUNBWHpiUU1hNEJOYlJFQnFwdThUSGJGKzdDcEdpcURzaW5hMTkxS3BjZCtsS0ZNaGtHTjZrbA0KNXFKTGxxWFJrQVg3T09oWGM4RGZYZnpwQ1NuWVNlK0kyeDBtTDJjQUxVc05ZYlpGRXRzNHJFeU9WM1hXMmdJeQ0Kd09Oa0VqY2hBb0dCQVBDR0N5WnZ2Vk5HSTVIWEVCRUhFdk11ZWhudDVlKy9wYnVDbWZhTVRNTmdyb2tIcFFGRA0KWU85aUJua3dRM2hSdzVQQm5SMFVOZkd0WWZuUDlYRlRZM1VYOUJsWURCbW50WlRSbU5VNzZVRWJ4elRKM0w4Zg0Kd2ZKVk5SMXR3V1NnNGQ5SnpkWVJOZlQxdHJtRi9sS1J3NzZzeitEMVV0NkNPTTl0OVE5TE1GaTFBb0dCQU5ldA0KbW83VEIxejNKVWMyNDlobmhOVTFLV3E3TVduZFNiSHptNldiMTlmYy9uTVFOcW9qRFZvT05kVSs5VGZnZWxPSA0KOXRXRkdoMGxKRklnaTh0UXdEcWg2bS96cGJORHh0QlN1R1B6T2U2Q0lVSUNUbk0wQ3d1QWFmeXJVaW1MM3B2bg0KZXNtWEhCL0k0VkFFK2NpK2laSFlJU1pUNzMxbklXdWlCYmU3WXdPOUFvR0JBSUpiTTZuV1A1YmxXWnZPSWxBSQ0KTkhZR0Iza01IV1d0eWFYeHAzNGZGZStCODdZaXBZUWt2MkdlRUFJWWJVakZqNmtCOHlQeWN6WVRrUmt5WTBUVA0KUEFFWFJWMkRBYlBaMkNqYTIra2RlbEttT25YYXZiLzc5MEplZWRZRVNSOC9yb3MwMWRFaUxNc2hiTEhwOUNkTw0KQnZmTmN6RHA1TXJoYXViSklscnlsalpOQW9HQkFOSkxUb0ZtV0M2WU9Edm8xRjVrQ1V2T0t4VUxjdEhUVjVEdw0KZzlvRlMzOEoxdndnV2Z5b2N0TlZPYjQwUmV0MnNDK1VTZVBGaFVIWHZrTnB3b1M2dHNRMHJoNzhoWnQyUVh0TQ0Kdk1lUUYvTnI1THUwL2dNc1FueXplQ1JLYzdGWTFQUlV6dytTakhTZGJMdVdMbXREQldZMFE1WllqeEpLSlhjSw0KSXVNVURpWk5Bb0dBUVZIcGhCZjhERmttZkNXQ3RBSEN1NWFMRFE4dFpDeEtjd0FFNEhLWm10WFVlWVB0U0F3Tw0KOW03Zi91Zml0bG95cVFjRm9WZEdkWURHYzRKNXRoKzV3MitaZ1VKREs5OTRFRUJwZU4xSE1DdjN4b3BreVpkcg0KM0hNemRvZm1LeTk0NjFZUEZVYlRldDhwR0VIV25CSzlQbFhaN0ZkSGNRRHEwaVV2VFcxQzNHcz0NCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kanali
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kanali
  template:
    metadata:
      labels:
        k8s-app: kanali
    spec:
      serviceAccountName: kanali
      containers:
      - name: kanali
        imagePullPolicy: IfNotPresent
        image: fbgrecojr/kanali:test
        command:
        - /kanali
        - start
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 443
        volumeMounts:
        - name: kanali
          mountPath: /etc/kanali
      volumes:
      - name: kanali
        projected:
          sources:
          - configMap:
              name: kanali-config
              items:
              - key: config.toml
                mode: 0644
                path: config.toml
          - secret:
              name: kanali
              items:
              - key: tls.crt
                path: pki/tls.crt
              - key: tls.key
                path: pki/tls.key
          - secret:
              name: kanali-key-decription
              items:
              - key: key.pem
                path: rsa/key.pem

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: kanali-config
  namespace: default
data:
  config.toml: |-
    [tracing]
    jaeger_server_url = "jaeger-agent.kube-system.svc.cluster.local"
    jaeger_agent_url = "jaeger-agent.kube-system.svc.cluster.local"

    [prometheus]
    port = 8000
    bind_address = "0.0.0.0"

    [plugins]
    location = "/"

    [plugins.apiKey]
    decryption_key_file = "/etc/kanali/rsa/key.pem"
    header_key = "apikey"

    [tls]
    cert_file = "/etc/kanali/pki/tls.crt"
    key_file = "/etc/kanali/pki/tls.key"
    ca_file = ""

    [server]
    secure_port = 8443
    insecure_port = 8080
    bind_address = "0.0.0.0"

    [process]
    log_level = "debug"

    [etcd]
    cert_file = ""
    key_file = ""
    ca_file = ""
    endpoints = "http://etcd-grpc-proxy:23790"
    prefix = "kanali"

    [proxy]
    enable_cluster_ip = true
    enable_mock_responses = true
    upstream_timeout = "0h0m10s"
    header_mask_value = "omitted"
    tls_common_name_validation = true
    mask_header_keys = [
      "apikey"
    ]

    [proxy.default_header_values]
    x-canary-deployment = "stable"

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kanali
  namespace: default
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: kanali
  targetCPUUtilizationPercentage: 500

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kanali
  name: kanali
  namespace: default

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kanali
rules:
  - apiGroups: ["kanali.io"]
    resources: ["apikeies", "apiproxies", "apikeybindings"]
    verbs: ["watch"]
  - apiGroups: ["extensions"]
    resources: ["thirdpartyresources"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["services", "secrets", "endpoints", "configmaps"]
    verbs: ["watch"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kanali
  labels:
    app: kanali
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kanali
subjects:
- kind: ServiceAccount
  name: kanali
  namespace: default
