---

kind: ConfigMap
apiVersion: v1
metadata:
  name: kanali-config
  namespace: default
data:
  config.toml: |-
    [tracing]
    jaeger_server_url = "jaeger-agent.kube-system.svc.cluster.local"
    jaeger_agent_url = "jaeger-agent.kube-system.svc.cluster.local"

    [plugins]
    location = "/"

    [plugins.apiKey]
    decryption_key_file = "/etc/pki/key.pem"
    header_key = "apikey"

    [tls]
    cert_file = "/etc/pki/tls.crt"
    key_file = "/etc/pki/tls.key"
    ca_file = ""

    [server]
    secure_port = 8443
    bind_address = "0.0.0.0"

    [process]
    log_level = "debug"

    [etcd]
    cert_file = ""
    key_file = ""
    ca_file = ""
    endpoints = "http://192.168.99.100:31747"
    prefix = "kanali"

    [proxy]
    enable_cluster_ip = true
    enable_mock_responses = true
    upstream_timeout = "0h0m10s"
    header_mask_value = "omitted"
    tls_common_name_validation = false
    mask_header_keys = [
      "apikey"
    ]

    [proxy.default_header_values]
    x-canary-deployment = "stable"
