---

kind: ConfigMap
apiVersion: v1
metadata:
  name: kanali-tracer-config
  namespace: {{default "default" .Values.kanali.namespace}}
data:
  tracer.yaml: |-
    ---
    sampler:
      type: const
      samplingServerURL: jaeger-agent.kube-system.svc.cluster.local
      param: 1
    reporter:
      logSpans: true
      localAgentHostPort: "jaeger-agent.kube-system.svc.cluster.local:5775"