# Default Helm values for kanali and its dependencies.

prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false

  serverFiles:
    prometheus.yml:
      scrape_configs:
      # Scrape config for service endpoints.
      #
      # The relabeling allows the actual service scrape endpoint to be configured
      # via the following annotations:
      #
      # * `prometheus.io/scrape`: Only scrape services that have a value of `true`
      # * `prometheus.io/scheme`: If the metrics endpoint is secured then you will need
      # to set this to `https` & most likely set the `tls_config` of the scrape config.
      # * `prometheus.io/path`: If the metrics path is not `/metrics` override this.
      # * `prometheus.io/port`: If the metrics are exposed on a different port to the
      # service then set this appropriately.
      - job_name: 'kubernetes-service-endpoints'

        kubernetes_sd_configs:
        - role: endpoints

        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name

grafana:
  server:
    service:
      type: NodePort
    adminUser: admin
    adminPassword: admin
    installPlugins: grafana-piechart-panel
    setDatasource:
      enabled: true
      restartPolicy: OnFailure
      backoffLimit: 3
      datasource:
        name: prometheus
        url: http://kanali-prometheus-server.default.svc.cluster.local
        type: prometheus
        access: proxy
        isDefault: true

jaeger:
  cassandra:
    config:
      max_heap_size: 1024M
      heap_new_size: 256M
    resources:
      requests:
        memory: 2048Mi
        cpu: 0.4
      limits:
        memory: 2048Mi
        cpu: 0.4

kanali:
  namespace: default
  gateway:
    securePort: 8443
    secureBindAddress: 0.0.0.0
    image:
      pullPolicy: IfNotPresent
      name: northwesternmutual/kanali
      tag: local
    scale:
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 500
  profiler:
    insecureBindAddress: 0.0.0.0
    insecurePort: 9090
  prometheus:
    insecureBindAddress: 0.0.0.0
    insecurePort: 9000


tags:
  metrics: true
  tracing: true